build: false

environment:

  matrix:
    - PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"
      MINICONDA: C:\Miniconda-x64
      REQUIREMENTS: "pytest numpy"
    - PYTHON_VERSION: "3.5.x"
      PYTHON_ARCH: "32"
      MINICONDA: C:\Miniconda35
      REQUIREMENTS: "pytest numpy pandas"
    - PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"
      MINICONDA: C:\Miniconda36-x64
      REQUIREMENTS: "pytest numpy pandas"


init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda install %REQUIREMENTS%
  - pip install -e .

test_script:
  - pytest -s neurtu/
